import { Cairo, Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/Redux/ReduxProvider";

const cairo = Cairo({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "استطلاعات",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <ReduxProvider>
        <body className={cairo.className}>{children}</body>
      </ReduxProvider>
    </html>
  );
}
